// 'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ClientRootLayout from "./client-root-layout";

// const theme = useMemo(() => getDesignTokens(mode), [mode]);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased vsc-initialized`}
//       >
//         <ThemeProvider theme={theme}>
//           <CssBaseline />
//         <header>
//           <Navbar />
//         </header>
//         {children}
//         <footer>
//           <Footer />
//         </footer>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return <ClientRootLayout>{children}</ClientRootLayout>;
}
